# DoneJS 0.5
FROM node:4.2

# DoneJS works best with npm version 2.x
RUN npm install -g npm@2.14

# Set environment variable for donejs version
ENV DONEJS_VERSION 0.5.7

# Install latest version of DoneJS
RUN npm install -g donejs@v0.5.7

CMD ["donejs"]
